apiVersion: v1
kind: Pod
metadata:
  name: web
  namespace: default
  labels:
    app: web
spec:
  containers:
  - name: web
    image: docker.io/igorpolicee/simple-golang-server:0.0.1
    volumeMounts:
    - mountPath: /app
      name: app

  initContainers:
  - name: init
    image: busybox:1.31.0
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
    - mountPath: /app
      name: app
  volumes:
  - name: app
    emptyDir: {}
